# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(300, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/login_black_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AuthDialog.setWindowIcon(icon)
        AuthDialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 229, 127, 255), stop:1 rgba(0, 131, 68, 255))")
        self.label = QtWidgets.QLabel(AuthDialog)
        self.label.setGeometry(QtCore.QRect(90, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label.setObjectName("label")
        self.old_pass = QtWidgets.QLineEdit(AuthDialog)
        self.old_pass.setGeometry(QtCore.QRect(85, 60, 130, 25))
        self.old_pass.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.old_pass.setInputMask("")
        self.old_pass.setText("")
        self.old_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.old_pass.setAlignment(QtCore.Qt.AlignCenter)
        self.old_pass.setObjectName("old_pass")
        self.pushButton = QtWidgets.QPushButton(AuthDialog)
        self.pushButton.setGeometry(QtCore.QRect(103, 120, 92, 28))
        self.pushButton.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(AuthDialog)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Авторизація"))
        self.label.setText(_translate("AuthDialog", "Введіть пароль:"))
        self.pushButton.setText(_translate("AuthDialog", "OK"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthDialog = QtWidgets.QDialog()
    ui = Ui_AuthDialog()
    ui.setupUi(AuthDialog)
    AuthDialog.show()
    sys.exit(app.exec_())
