# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.inputs = []
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1011, 817)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/construction_black_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 229, 127, 255), stop:1 rgba(0, 131, 68, 255))")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 431, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.dev_1 = QtWidgets.QFrame(self.centralwidget)
        self.dev_1.setGeometry(QtCore.QRect(10, 230, 491, 261))
        self.dev_1.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.dev_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dev_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dev_1.setObjectName("dev_1")
        self.label_2 = QtWidgets.QLabel(self.dev_1)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.dev_1)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.n_max_p = QtWidgets.QLineEdit(self.dev_1)
        self.n_max_p.setGeometry(QtCore.QRect(230, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_p.setFont(font)
        self.n_max_p.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_p.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_p.setObjectName("n_max_p")
        self.inputs.append(self.n_max_p)
        self.label_4 = QtWidgets.QLabel(self.dev_1)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.n_max_q = QtWidgets.QLineEdit(self.dev_1)
        self.n_max_q.setGeometry(QtCore.QRect(230, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_q.setFont(font)
        self.n_max_q.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_q.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_q.setObjectName("n_max_q")
        self.inputs.append(self.n_max_q)
        self.label_5 = QtWidgets.QLabel(self.dev_1)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_5.setObjectName("label_5")
        self.eff_coef_max = QtWidgets.QLineEdit(self.dev_1)
        self.eff_coef_max.setGeometry(QtCore.QRect(230, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_max.setFont(font)
        self.eff_coef_max.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_max.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_max.setObjectName("eff_coef_max")
        self.inputs.append(self.eff_coef_max)
        self.eff_coef_min = QtWidgets.QLineEdit(self.dev_1)
        self.eff_coef_min.setGeometry(QtCore.QRect(230, 190, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_min.setFont(font)
        self.eff_coef_min.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_min.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_min.setClearButtonEnabled(False)
        self.eff_coef_min.setObjectName("eff_coef_min")
        self.inputs.append(self.eff_coef_min)
        self.label_6 = QtWidgets.QLabel(self.dev_1)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_6.setObjectName("label_6")
        self.n_min_p = QtWidgets.QLineEdit(self.dev_1)
        self.n_min_p.setGeometry(QtCore.QRect(230, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_p.setFont(font)
        self.n_min_p.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_p.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_p.setObjectName("n_min_p")
        self.inputs.append(self.n_min_p)
        self.n_min_q = QtWidgets.QLineEdit(self.dev_1)
        self.n_min_q.setGeometry(QtCore.QRect(230, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_q.setFont(font)
        self.n_min_q.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_q.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_q.setObjectName("n_min_q")
        self.inputs.append(self.n_min_q)
        self.label_7 = QtWidgets.QLabel(self.dev_1)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.dev_1)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.dev_1)
        self.label_9.setGeometry(QtCore.QRect(400, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_9.setObjectName("label_9")
        self.q_max_dev = QtWidgets.QLabel(self.dev_1)
        self.q_max_dev.setGeometry(QtCore.QRect(390, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_dev.setFont(font)
        self.q_max_dev.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_dev.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_dev.setObjectName("q_max_dev")
        self.label_12 = QtWidgets.QLabel(self.dev_1)
        self.label_12.setGeometry(QtCore.QRect(400, 130, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_12.setObjectName("label_12")
        self.q_min_dev = QtWidgets.QLabel(self.dev_1)
        self.q_min_dev.setGeometry(QtCore.QRect(390, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_dev.setFont(font)
        self.q_min_dev.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_dev.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_dev.setObjectName("q_min_dev")
        self.btn_add_2 = QtWidgets.QPushButton(self.dev_1)
        self.btn_add_2.setGeometry(QtCore.QRect(450, 220, 30, 30))
        self.btn_add_2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/post_add_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_2.setIcon(icon1)
        self.btn_add_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_2.setObjectName("btn_add_2")
        self.quantity = QtWidgets.QLineEdit(self.dev_1)
        self.quantity.setGeometry(QtCore.QRect(290, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.quantity.setFont(font)
        self.quantity.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.quantity.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity.setObjectName("quantity")
        self.inputs.append(self.quantity)
        self.label_11 = QtWidgets.QLabel(self.dev_1)
        self.label_11.setGeometry(QtCore.QRect(210, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_11.setObjectName("label_11")
        self.dev_2 = QtWidgets.QFrame(self.centralwidget)
        self.dev_2.setGeometry(QtCore.QRect(510, 230, 491, 261))
        self.dev_2.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.dev_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dev_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dev_2.setObjectName("dev_2")
        self.label_14 = QtWidgets.QLabel(self.dev_2)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.dev_2)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_15.setObjectName("label_15")
        self.n_max_p_2 = QtWidgets.QLineEdit(self.dev_2)
        self.n_max_p_2.setGeometry(QtCore.QRect(230, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_p_2.setFont(font)
        self.n_max_p_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_p_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_p_2.setObjectName("n_max_p_2")
        self.inputs.append(self.n_max_p_2)
        self.label_16 = QtWidgets.QLabel(self.dev_2)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_16.setObjectName("label_16")
        self.n_max_q_2 = QtWidgets.QLineEdit(self.dev_2)
        self.n_max_q_2.setGeometry(QtCore.QRect(230, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_q_2.setFont(font)
        self.n_max_q_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_q_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_q_2.setObjectName("n_max_q_2")
        self.inputs.append(self.n_max_q_2)
        self.label_17 = QtWidgets.QLabel(self.dev_2)
        self.label_17.setGeometry(QtCore.QRect(10, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_17.setObjectName("label_17")
        self.eff_coef_max_2 = QtWidgets.QLineEdit(self.dev_2)
        self.eff_coef_max_2.setGeometry(QtCore.QRect(230, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_max_2.setFont(font)
        self.eff_coef_max_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_max_2.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_max_2.setObjectName("eff_coef_max_2")
        self.inputs.append(self.eff_coef_max_2)
        self.eff_coef_min_2 = QtWidgets.QLineEdit(self.dev_2)
        self.eff_coef_min_2.setGeometry(QtCore.QRect(230, 190, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_min_2.setFont(font)
        self.eff_coef_min_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_min_2.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_min_2.setClearButtonEnabled(False)
        self.eff_coef_min_2.setObjectName("eff_coef_min_2")
        self.inputs.append(self.eff_coef_min_2)
        self.label_18 = QtWidgets.QLabel(self.dev_2)
        self.label_18.setGeometry(QtCore.QRect(10, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_18.setObjectName("label_18")
        self.n_min_p_2 = QtWidgets.QLineEdit(self.dev_2)
        self.n_min_p_2.setGeometry(QtCore.QRect(230, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_p_2.setFont(font)
        self.n_min_p_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_p_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_p_2.setObjectName("n_min_p_2")
        self.inputs.append(self.n_min_p_2)
        self.n_min_q_2 = QtWidgets.QLineEdit(self.dev_2)
        self.n_min_q_2.setGeometry(QtCore.QRect(230, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_q_2.setFont(font)
        self.n_min_q_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_q_2.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_q_2.setObjectName("n_min_q_2")
        self.inputs.append(self.n_min_q_2)
        self.label_19 = QtWidgets.QLabel(self.dev_2)
        self.label_19.setGeometry(QtCore.QRect(10, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.dev_2)
        self.label_20.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.dev_2)
        self.label_21.setGeometry(QtCore.QRect(400, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_21.setObjectName("label_21")
        self.q_max_dev_2 = QtWidgets.QLabel(self.dev_2)
        self.q_max_dev_2.setGeometry(QtCore.QRect(390, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_dev_2.setFont(font)
        self.q_max_dev_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_dev_2.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_dev_2.setObjectName("q_max_dev_2")
        self.label_23 = QtWidgets.QLabel(self.dev_2)
        self.label_23.setGeometry(QtCore.QRect(400, 130, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_23.setObjectName("label_23")
        self.q_min_dev_2 = QtWidgets.QLabel(self.dev_2)
        self.q_min_dev_2.setGeometry(QtCore.QRect(390, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_dev_2.setFont(font)
        self.q_min_dev_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_dev_2.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_dev_2.setObjectName("q_min_dev_2")
        self.btn_add_3 = QtWidgets.QPushButton(self.dev_2)
        self.btn_add_3.setGeometry(QtCore.QRect(450, 220, 30, 30))
        self.btn_add_3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_3.setText("")
        self.btn_add_3.setIcon(icon1)
        self.btn_add_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_3.setObjectName("btn_add_3")
        self.btn_del_2 = QtWidgets.QPushButton(self.dev_2)
        self.btn_del_2.setGeometry(QtCore.QRect(410, 220, 30, 30))
        self.btn_del_2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_del_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/delete_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del_2.setIcon(icon2)
        self.btn_del_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_del_2.setObjectName("btn_del_2")
        self.quantity_2 = QtWidgets.QLineEdit(self.dev_2)
        self.quantity_2.setGeometry(QtCore.QRect(290, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.quantity_2.setFont(font)
        self.quantity_2.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.quantity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity_2.setObjectName("quantity_2")
        self.inputs.append(self.quantity_2)
        self.label_25 = QtWidgets.QLabel(self.dev_2)
        self.label_25.setGeometry(QtCore.QRect(210, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_25.setObjectName("label_25")
        self.btn_add_pg_2 = QtWidgets.QPushButton(self.dev_2)
        self.btn_add_pg_2.setGeometry(QtCore.QRect(450, 10, 30, 30))
        self.btn_add_pg_2.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_pg_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/dashboard_customize_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_pg_2.setIcon(icon3)
        self.btn_add_pg_2.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_pg_2.setObjectName("btn_add_pg_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(240, 70, 261, 71))
        self.frame_3.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(40, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_33.setObjectName("label_33")
        self.q_max_go = QtWidgets.QLabel(self.frame_3)
        self.q_max_go.setGeometry(QtCore.QRect(40, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_go.setFont(font)
        self.q_max_go.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_go.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_go.setObjectName("q_max_go")
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setGeometry(QtCore.QRect(160, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_35.setObjectName("label_35")
        self.q_min_go = QtWidgets.QLabel(self.frame_3)
        self.q_min_go.setGeometry(QtCore.QRect(160, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_go.setFont(font)
        self.q_min_go.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_go.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_go.setObjectName("q_min_go")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(510, 70, 221, 71))
        self.frame_4.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_37 = QtWidgets.QLabel(self.frame_4)
        self.label_37.setGeometry(QtCore.QRect(40, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_37.setObjectName("label_37")
        self.gl_type = QtWidgets.QLabel(self.frame_4)
        self.gl_type.setGeometry(QtCore.QRect(130, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gl_type.setFont(font)
        self.gl_type.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.gl_type.setAlignment(QtCore.Qt.AlignCenter)
        self.gl_type.setObjectName("gl_type")
        self.label_39 = QtWidgets.QLabel(self.frame_4)
        self.label_39.setGeometry(QtCore.QRect(10, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_39.setObjectName("label_39")
        self.gl_min = QtWidgets.QLabel(self.frame_4)
        self.gl_min.setGeometry(QtCore.QRect(70, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gl_min.setFont(font)
        self.gl_min.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.gl_min.setObjectName("gl_min")
        self.gl_max = QtWidgets.QLabel(self.frame_4)
        self.gl_max.setGeometry(QtCore.QRect(180, 40, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gl_max.setFont(font)
        self.gl_max.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.gl_max.setObjectName("gl_max")
        self.label_42 = QtWidgets.QLabel(self.frame_4)
        self.label_42.setGeometry(QtCore.QRect(120, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_42.setObjectName("label_42")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(10, 70, 221, 71))
        self.frame_5.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_43 = QtWidgets.QLabel(self.frame_5)
        self.label_43.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_43.setObjectName("label_43")
        self.q_max_sum = QtWidgets.QLabel(self.frame_5)
        self.q_max_sum.setGeometry(QtCore.QRect(30, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_sum.setFont(font)
        self.q_max_sum.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_sum.setObjectName("q_max_sum")
        self.label_45 = QtWidgets.QLabel(self.frame_5)
        self.label_45.setGeometry(QtCore.QRect(130, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_45.setObjectName("label_45")
        self.q_min_sum = QtWidgets.QLabel(self.frame_5)
        self.q_min_sum.setGeometry(QtCore.QRect(130, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_sum.setFont(font)
        self.q_min_sum.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_sum.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_sum.setObjectName("q_min_sum")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(740, 70, 261, 71))
        self.frame_6.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 20, 30, 30))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/login_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 20, 30, 30))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.pushButton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons/upload_file_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setGeometry(QtCore.QRect(80, 20, 30, 30))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.pushButton_8.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons/print_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 20, 30, 30))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.pushButton_9.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons/settings_white_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon7)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.calc_data = QtWidgets.QFrame(self.centralwidget)
        self.calc_data.setGeometry(QtCore.QRect(10, 150, 991, 71))
        self.calc_data.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.calc_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calc_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.calc_data.setObjectName("calc_data")
        self.t_max_c = QtWidgets.QLineEdit(self.calc_data)
        self.t_max_c.setGeometry(QtCore.QRect(90, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.t_max_c.setFont(font)
        self.t_max_c.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.t_max_c.setAlignment(QtCore.Qt.AlignCenter)
        self.t_max_c.setObjectName("t_max_c")
        self.inputs.append(self.t_max_c)
        self.label_26 = QtWidgets.QLabel(self.calc_data)
        self.label_26.setGeometry(QtCore.QRect(20, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_26.setObjectName("label_26")
        self.t_min_c = QtWidgets.QLineEdit(self.calc_data)
        self.t_min_c.setGeometry(QtCore.QRect(90, 40, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.t_min_c.setFont(font)
        self.t_min_c.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.t_min_c.setAlignment(QtCore.Qt.AlignCenter)
        self.t_min_c.setObjectName("t_min_c")
        self.inputs.append(self.t_min_c)
        self.label_27 = QtWidgets.QLabel(self.calc_data)
        self.label_27.setGeometry(QtCore.QRect(20, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_27.setObjectName("label_27")
        self.p_max_nad = QtWidgets.QLineEdit(self.calc_data)
        self.p_max_nad.setGeometry(QtCore.QRect(270, 10, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.p_max_nad.setFont(font)
        self.p_max_nad.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.p_max_nad.setAlignment(QtCore.Qt.AlignCenter)
        self.p_max_nad.setObjectName("p_max_nad")
        self.inputs.append(self.p_max_nad)
        self.label_28 = QtWidgets.QLabel(self.calc_data)
        self.label_28.setGeometry(QtCore.QRect(150, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_28.setObjectName("label_28")
        self.p_min_nad = QtWidgets.QLineEdit(self.calc_data)
        self.p_min_nad.setGeometry(QtCore.QRect(270, 40, 71, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.p_min_nad.setFont(font)
        self.p_min_nad.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.p_min_nad.setAlignment(QtCore.Qt.AlignCenter)
        self.p_min_nad.setObjectName("p_min_nad")
        self.inputs.append(self.p_min_nad)
        self.label_29 = QtWidgets.QLabel(self.calc_data)
        self.label_29.setGeometry(QtCore.QRect(150, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.calc_data)
        self.label_30.setGeometry(QtCore.QRect(360, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_30.setObjectName("label_30")
        self.t_max_k = QtWidgets.QLabel(self.calc_data)
        self.t_max_k.setGeometry(QtCore.QRect(430, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.t_max_k.setFont(font)
        self.t_max_k.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.t_max_k.setObjectName("t_max_k")
        self.t_min_k = QtWidgets.QLabel(self.calc_data)
        self.t_min_k.setGeometry(QtCore.QRect(430, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.t_min_k.setFont(font)
        self.t_min_k.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.t_min_k.setObjectName("t_min_k")
        self.label_47 = QtWidgets.QLabel(self.calc_data)
        self.label_47.setGeometry(QtCore.QRect(360, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.calc_data)
        self.label_48.setGeometry(QtCore.QRect(600, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.calc_data)
        self.label_49.setGeometry(QtCore.QRect(490, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.calc_data)
        self.label_50.setGeometry(QtCore.QRect(600, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.calc_data)
        self.label_51.setGeometry(QtCore.QRect(490, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_51.setObjectName("label_51")
        self.p_max_bar = QtWidgets.QLabel(self.calc_data)
        self.p_max_bar.setGeometry(QtCore.QRect(780, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.p_max_bar.setFont(font)
        self.p_max_bar.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.p_max_bar.setObjectName("p_max_bar")
        self.label_53 = QtWidgets.QLabel(self.calc_data)
        self.label_53.setGeometry(QtCore.QRect(670, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_53.setObjectName("label_53")
        self.p_min_bar = QtWidgets.QLabel(self.calc_data)
        self.p_min_bar.setGeometry(QtCore.QRect(780, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.p_min_bar.setFont(font)
        self.p_min_bar.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.p_min_bar.setObjectName("p_min_bar")
        self.label_55 = QtWidgets.QLabel(self.calc_data)
        self.label_55.setGeometry(QtCore.QRect(670, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_55.setObjectName("label_55")
        self.z_max = QtWidgets.QLabel(self.calc_data)
        self.z_max.setGeometry(QtCore.QRect(910, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.z_max.setFont(font)
        self.z_max.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.z_max.setObjectName("z_max")
        self.label_57 = QtWidgets.QLabel(self.calc_data)
        self.label_57.setGeometry(QtCore.QRect(850, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_57.setObjectName("label_57")
        self.z_min = QtWidgets.QLabel(self.calc_data)
        self.z_min.setGeometry(QtCore.QRect(910, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.z_min.setFont(font)
        self.z_min.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.z_min.setObjectName("z_min")
        self.label_59 = QtWidgets.QLabel(self.calc_data)
        self.label_59.setGeometry(QtCore.QRect(850, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_59.setObjectName("label_59")
        self.dev_3 = QtWidgets.QFrame(self.centralwidget)
        self.dev_3.setGeometry(QtCore.QRect(10, 500, 491, 261))
        self.dev_3.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.dev_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dev_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dev_3.setObjectName("dev_3")
        self.label_60 = QtWidgets.QLabel(self.dev_3)
        self.label_60.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.dev_3)
        self.label_61.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_61.setObjectName("label_61")
        self.n_max_p_3 = QtWidgets.QLineEdit(self.dev_3)
        self.n_max_p_3.setGeometry(QtCore.QRect(230, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_p_3.setFont(font)
        self.n_max_p_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_p_3.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_p_3.setObjectName("n_max_p_3")
        self.inputs.append(self.n_max_p_3)
        self.label_62 = QtWidgets.QLabel(self.dev_3)
        self.label_62.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_62.setObjectName("label_62")
        self.n_max_q_3 = QtWidgets.QLineEdit(self.dev_3)
        self.n_max_q_3.setGeometry(QtCore.QRect(230, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_q_3.setFont(font)
        self.n_max_q_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_q_3.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_q_3.setObjectName("n_max_q_3")
        self.inputs.append(self.n_max_q_3)
        self.label_63 = QtWidgets.QLabel(self.dev_3)
        self.label_63.setGeometry(QtCore.QRect(10, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_63.setObjectName("label_63")
        self.eff_coef_max_3 = QtWidgets.QLineEdit(self.dev_3)
        self.eff_coef_max_3.setGeometry(QtCore.QRect(230, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_max_3.setFont(font)
        self.eff_coef_max_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_max_3.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_max_3.setObjectName("eff_coef_max_3")
        self.inputs.append(self.eff_coef_max_3)
        self.eff_coef_min_3 = QtWidgets.QLineEdit(self.dev_3)
        self.eff_coef_min_3.setGeometry(QtCore.QRect(230, 190, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_min_3.setFont(font)
        self.eff_coef_min_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_min_3.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_min_3.setClearButtonEnabled(False)
        self.eff_coef_min_3.setObjectName("eff_coef_min_3")
        self.inputs.append(self.eff_coef_min_3)
        self.label_64 = QtWidgets.QLabel(self.dev_3)
        self.label_64.setGeometry(QtCore.QRect(10, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_64.setObjectName("label_64")
        self.n_min_p_3 = QtWidgets.QLineEdit(self.dev_3)
        self.n_min_p_3.setGeometry(QtCore.QRect(230, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_p_3.setFont(font)
        self.n_min_p_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_p_3.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_p_3.setObjectName("n_min_p_3")
        self.inputs.append(self.n_min_p_3)
        self.n_min_q_3 = QtWidgets.QLineEdit(self.dev_3)
        self.n_min_q_3.setGeometry(QtCore.QRect(230, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_q_3.setFont(font)
        self.n_min_q_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_q_3.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_q_3.setObjectName("n_min_q_3")
        self.inputs.append(self.n_min_q_3)
        self.label_65 = QtWidgets.QLabel(self.dev_3)
        self.label_65.setGeometry(QtCore.QRect(10, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.dev_3)
        self.label_66.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.dev_3)
        self.label_67.setGeometry(QtCore.QRect(400, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_67.setObjectName("label_67")
        self.q_max_dev_3 = QtWidgets.QLabel(self.dev_3)
        self.q_max_dev_3.setGeometry(QtCore.QRect(390, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_dev_3.setFont(font)
        self.q_max_dev_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_dev_3.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_dev_3.setObjectName("q_max_dev_3")
        self.label_69 = QtWidgets.QLabel(self.dev_3)
        self.label_69.setGeometry(QtCore.QRect(400, 130, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_69.setObjectName("label_69")
        self.q_min_dev_3 = QtWidgets.QLabel(self.dev_3)
        self.q_min_dev_3.setGeometry(QtCore.QRect(390, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_dev_3.setFont(font)
        self.q_min_dev_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_dev_3.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_dev_3.setObjectName("q_min_dev_3")
        self.btn_add_4 = QtWidgets.QPushButton(self.dev_3)
        self.btn_add_4.setGeometry(QtCore.QRect(450, 220, 30, 30))
        self.btn_add_4.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_4.setText("")
        self.btn_add_4.setIcon(icon1)
        self.btn_add_4.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_4.setObjectName("btn_add_4")
        self.btn_del_3 = QtWidgets.QPushButton(self.dev_3)
        self.btn_del_3.setGeometry(QtCore.QRect(410, 220, 30, 30))
        self.btn_del_3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_del_3.setText("")
        self.btn_del_3.setIcon(icon2)
        self.btn_del_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_del_3.setObjectName("btn_del_3")
        self.quantity_3 = QtWidgets.QLineEdit(self.dev_3)
        self.quantity_3.setGeometry(QtCore.QRect(290, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.quantity_3.setFont(font)
        self.quantity_3.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.quantity_3.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity_3.setObjectName("quantity_3")
        self.inputs.append(self.quantity_3)
        self.label_71 = QtWidgets.QLabel(self.dev_3)
        self.label_71.setGeometry(QtCore.QRect(210, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_71.setObjectName("label_71")
        self.btn_add_pg_3 = QtWidgets.QPushButton(self.dev_3)
        self.btn_add_pg_3.setGeometry(QtCore.QRect(450, 10, 30, 30))
        self.btn_add_pg_3.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_pg_3.setText("")
        self.btn_add_pg_3.setIcon(icon3)
        self.btn_add_pg_3.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_pg_3.setObjectName("btn_add_pg_3")
        self.dev_4 = QtWidgets.QFrame(self.centralwidget)
        self.dev_4.setGeometry(QtCore.QRect(510, 500, 491, 261))
        self.dev_4.setStyleSheet("background-color: rgba(255,255,255,20);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.dev_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dev_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dev_4.setObjectName("dev_4")
        self.label_72 = QtWidgets.QLabel(self.dev_4)
        self.label_72.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.dev_4)
        self.label_73.setGeometry(QtCore.QRect(10, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_73.setObjectName("label_73")
        self.n_max_p_4 = QtWidgets.QLineEdit(self.dev_4)
        self.n_max_p_4.setGeometry(QtCore.QRect(230, 40, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_p_4.setFont(font)
        self.n_max_p_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_p_4.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_p_4.setObjectName("n_max_p_4")
        self.inputs.append(self.n_max_p_4)
        self.label_74 = QtWidgets.QLabel(self.dev_4)
        self.label_74.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_74.setObjectName("label_74")
        self.n_max_q_4 = QtWidgets.QLineEdit(self.dev_4)
        self.n_max_q_4.setGeometry(QtCore.QRect(230, 70, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_max_q_4.setFont(font)
        self.n_max_q_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_max_q_4.setAlignment(QtCore.Qt.AlignCenter)
        self.n_max_q_4.setObjectName("n_max_q_4")
        self.inputs.append(self.n_max_q_4)
        self.label_75 = QtWidgets.QLabel(self.dev_4)
        self.label_75.setGeometry(QtCore.QRect(10, 100, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_75.setObjectName("label_75")
        self.eff_coef_max_4 = QtWidgets.QLineEdit(self.dev_4)
        self.eff_coef_max_4.setGeometry(QtCore.QRect(230, 100, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_max_4.setFont(font)
        self.eff_coef_max_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_max_4.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_max_4.setObjectName("eff_coef_max_4")
        self.inputs.append(self.eff_coef_max_4)
        self.eff_coef_min_4 = QtWidgets.QLineEdit(self.dev_4)
        self.eff_coef_min_4.setGeometry(QtCore.QRect(230, 190, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.eff_coef_min_4.setFont(font)
        self.eff_coef_min_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.eff_coef_min_4.setAlignment(QtCore.Qt.AlignCenter)
        self.eff_coef_min_4.setClearButtonEnabled(False)
        self.eff_coef_min_4.setObjectName("eff_coef_min_4")
        self.inputs.append(self.eff_coef_min_4)
        self.label_76 = QtWidgets.QLabel(self.dev_4)
        self.label_76.setGeometry(QtCore.QRect(10, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_76.setObjectName("label_76")
        self.n_min_p_4 = QtWidgets.QLineEdit(self.dev_4)
        self.n_min_p_4.setGeometry(QtCore.QRect(230, 130, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_p_4.setFont(font)
        self.n_min_p_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_p_4.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_p_4.setObjectName("n_min_p_4")
        self.inputs.append(self.n_min_p_4)
        self.n_min_q_4 = QtWidgets.QLineEdit(self.dev_4)
        self.n_min_q_4.setGeometry(QtCore.QRect(230, 160, 110, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.n_min_q_4.setFont(font)
        self.n_min_q_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.n_min_q_4.setAlignment(QtCore.Qt.AlignCenter)
        self.n_min_q_4.setObjectName("n_min_q_4")
        self.inputs.append(self.n_min_q_4)
        self.label_77 = QtWidgets.QLabel(self.dev_4)
        self.label_77.setGeometry(QtCore.QRect(10, 130, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.dev_4)
        self.label_78.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.dev_4)
        self.label_79.setGeometry(QtCore.QRect(400, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_79.setObjectName("label_79")
        self.q_max_dev_4 = QtWidgets.QLabel(self.dev_4)
        self.q_max_dev_4.setGeometry(QtCore.QRect(390, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_max_dev_4.setFont(font)
        self.q_max_dev_4.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_max_dev_4.setAlignment(QtCore.Qt.AlignCenter)
        self.q_max_dev_4.setObjectName("q_max_dev_4")
        self.label_81 = QtWidgets.QLabel(self.dev_4)
        self.label_81.setGeometry(QtCore.QRect(400, 130, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_81.setObjectName("label_81")
        self.q_min_dev_4 = QtWidgets.QLabel(self.dev_4)
        self.q_min_dev_4.setGeometry(QtCore.QRect(390, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.q_min_dev_4.setFont(font)
        self.q_min_dev_4.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.q_min_dev_4.setAlignment(QtCore.Qt.AlignCenter)
        self.q_min_dev_4.setObjectName("q_min_dev_4")
        self.btn_del_4 = QtWidgets.QPushButton(self.dev_4)
        self.btn_del_4.setGeometry(QtCore.QRect(410, 220, 30, 30))
        self.btn_del_4.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_del_4.setText("")
        self.btn_del_4.setIcon(icon2)
        self.btn_del_4.setIconSize(QtCore.QSize(30, 30))
        self.btn_del_4.setObjectName("btn_del_4")
        self.quantity_4 = QtWidgets.QLineEdit(self.dev_4)
        self.quantity_4.setGeometry(QtCore.QRect(290, 10, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.quantity_4.setFont(font)
        self.quantity_4.setStyleSheet("border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.quantity_4.setAlignment(QtCore.Qt.AlignCenter)
        self.quantity_4.setObjectName("quantity_4")
        self.inputs.append(self.quantity_4)
        self.label_83 = QtWidgets.QLabel(self.dev_4)
        self.label_83.setGeometry(QtCore.QRect(210, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_83.setObjectName("label_83")
        self.btn_add_pg_4 = QtWidgets.QPushButton(self.dev_4)
        self.btn_add_pg_4.setGeometry(QtCore.QRect(450, 10, 30, 30))
        self.btn_add_pg_4.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,55);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btn_add_pg_4.setText("")
        self.btn_add_pg_4.setIcon(icon3)
        self.btn_add_pg_4.setIconSize(QtCore.QSize(30, 30))
        self.btn_add_pg_4.setObjectName("btn_add_pg_4")
        self.label_85 = QtWidgets.QLabel(self.centralwidget)
        self.label_85.setGeometry(QtCore.QRect(410, 780, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_85.setScaledContents(True)
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.centralwidget)
        self.label_86.setGeometry(QtCore.QRect(500, 780, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_86.setText("")
        self.label_86.setPixmap(QtGui.QPixmap("Icons/python-3.svg"))
        self.label_86.setScaledContents(True)
        self.label_86.setObjectName("label_86")
        self.label_84 = QtWidgets.QLabel(self.centralwidget)
        self.label_84.setGeometry(QtCore.QRect(10, 10, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("color: white;\n"
"background-color: rgba(255,255,255,30);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-radius: 10px")
        self.label_84.setText("")
        self.label_84.setPixmap(QtGui.QPixmap(":/icons/Icons/construction_white_36dp.svg"))
        self.label_84.setScaledContents(True)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Розрахунки ГАЗ"))
        self.label.setText(_translate("MainWindow", "РОЗРАХУНОК ЛІЧИЛЬНИКА"))
        self.label_2.setText(_translate("MainWindow", "Прилад 1"))
        self.label_3.setText(_translate("MainWindow", "MAX потужність, кВт"))
        self.n_max_p.setText(_translate("MainWindow", "0"))
        self.n_max_p.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "MAX навантаження, кВт"))
        self.n_max_q.setText(_translate("MainWindow", "0"))
        self.n_max_q.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "MAX ККД"))
        self.eff_coef_max.setText(_translate("MainWindow", "1"))
        self.eff_coef_max.setPlaceholderText(_translate("MainWindow", "1"))
        self.eff_coef_min.setText(_translate("MainWindow", "1"))
        self.eff_coef_min.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_6.setText(_translate("MainWindow", "MIN ККД"))
        self.n_min_p.setText(_translate("MainWindow", "0"))
        self.n_min_p.setPlaceholderText(_translate("MainWindow", "0"))
        self.n_min_q.setText(_translate("MainWindow", "0"))
        self.n_min_q.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "MIN потужність, кВт"))
        self.label_8.setText(_translate("MainWindow", "MIN навантаження, кВт"))
        self.label_9.setText(_translate("MainWindow", "Qmax"))
        self.q_max_dev.setText(_translate("MainWindow", "15.18"))
        self.label_12.setText(_translate("MainWindow", "Qmin"))
        self.q_min_dev.setText(_translate("MainWindow", "0.051"))
        self.quantity.setText(_translate("MainWindow", "1"))
        self.quantity.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "Кількість"))
        self.label_14.setText(_translate("MainWindow", "Прилад 2"))
        self.label_15.setText(_translate("MainWindow", "MAX потужність, кВт"))
        self.n_max_p_2.setText(_translate("MainWindow", "0"))
        self.n_max_p_2.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "MAX навантаження, кВт"))
        self.n_max_q_2.setText(_translate("MainWindow", "0"))
        self.n_max_q_2.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "MAX ККД"))
        self.eff_coef_max_2.setText(_translate("MainWindow", "1"))
        self.eff_coef_max_2.setPlaceholderText(_translate("MainWindow", "1"))
        self.eff_coef_min_2.setText(_translate("MainWindow", "1"))
        self.eff_coef_min_2.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "MIN ККД"))
        self.n_min_p_2.setText(_translate("MainWindow", "0"))
        self.n_min_p_2.setPlaceholderText(_translate("MainWindow", "0"))
        self.n_min_q_2.setText(_translate("MainWindow", "0"))
        self.n_min_q_2.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "MIN потужність, кВт"))
        self.label_20.setText(_translate("MainWindow", "MIN навантаження, кВт"))
        self.label_21.setText(_translate("MainWindow", "Qmax"))
        self.q_max_dev_2.setText(_translate("MainWindow", "15.18"))
        self.label_23.setText(_translate("MainWindow", "Qmin"))
        self.q_min_dev_2.setText(_translate("MainWindow", "0.051"))
        self.quantity_2.setText(_translate("MainWindow", "1"))
        self.quantity_2.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_25.setText(_translate("MainWindow", "Кількість"))
        self.label_33.setText(_translate("MainWindow", "Qmax. го"))
        self.q_max_go.setText(_translate("MainWindow", "15.18"))
        self.label_35.setText(_translate("MainWindow", "Qmin. го"))
        self.q_min_go.setText(_translate("MainWindow", "0.051"))
        self.label_37.setText(_translate("MainWindow", "Типорозмір:"))
        self.gl_type.setText(_translate("MainWindow", "G4"))
        self.label_39.setText(_translate("MainWindow", "Qmin.:"))
        self.gl_min.setText(_translate("MainWindow", "0.016"))
        self.gl_max.setText(_translate("MainWindow", "6.0"))
        self.label_42.setText(_translate("MainWindow", "Qmax.:"))
        self.label_43.setText(_translate("MainWindow", "Qmax. сум"))
        self.q_max_sum.setText(_translate("MainWindow", "15.18"))
        self.label_45.setText(_translate("MainWindow", "Qmin. заг"))
        self.q_min_sum.setText(_translate("MainWindow", "0.051"))
        self.t_max_c.setText(_translate("MainWindow", "40"))
        self.t_max_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "Tmax, C"))
        self.t_min_c.setText(_translate("MainWindow", "-25"))
        self.t_min_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "Tmin, C"))
        self.p_max_nad.setText(_translate("MainWindow", "0.003"))
        self.p_max_nad.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_28.setText(_translate("MainWindow", "Pmax над, МПа"))
        self.p_min_nad.setText(_translate("MainWindow", "0.001"))
        self.p_min_nad.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "Pmin над, МПа"))
        self.label_30.setText(_translate("MainWindow", "Tmax, K:"))
        self.t_max_k.setText(_translate("MainWindow", "313.2"))
        self.t_min_k.setText(_translate("MainWindow", "248.2"))
        self.label_47.setText(_translate("MainWindow", "Tmin, K:"))
        self.label_48.setText(_translate("MainWindow", "0.102"))
        self.label_49.setText(_translate("MainWindow", "Pmax b, МПа:"))
        self.label_50.setText(_translate("MainWindow", "0.098"))
        self.label_51.setText(_translate("MainWindow", "Pmin b, МПа:"))
        self.p_max_bar.setText(_translate("MainWindow", "0.105"))
        self.label_53.setText(_translate("MainWindow", "Pmax a, МПа:"))
        self.p_min_bar.setText(_translate("MainWindow", "0.099"))
        self.label_55.setText(_translate("MainWindow", "Pmin a, МПа:"))
        self.z_max.setText(_translate("MainWindow", "0.99407"))
        self.label_57.setText(_translate("MainWindow", "Zmax:"))
        self.z_min.setText(_translate("MainWindow", "0.98746"))
        self.label_59.setText(_translate("MainWindow", "Zmin:"))
        self.label_60.setText(_translate("MainWindow", "Прилад 3"))
        self.label_61.setText(_translate("MainWindow", "MAX потужність, кВт"))
        self.n_max_p_3.setText(_translate("MainWindow", "0"))
        self.n_max_p_3.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_62.setText(_translate("MainWindow", "MAX навантаження, кВт"))
        self.n_max_q_3.setText(_translate("MainWindow", "0"))
        self.n_max_q_3.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_63.setText(_translate("MainWindow", "MAX ККД"))
        self.eff_coef_max_3.setText(_translate("MainWindow", "1"))
        self.eff_coef_max_3.setPlaceholderText(_translate("MainWindow", "1"))
        self.eff_coef_min_3.setText(_translate("MainWindow", "1"))
        self.eff_coef_min_3.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_64.setText(_translate("MainWindow", "MIN ККД"))
        self.n_min_p_3.setText(_translate("MainWindow", "0"))
        self.n_min_p_3.setPlaceholderText(_translate("MainWindow", "0"))
        self.n_min_q_3.setText(_translate("MainWindow", "0"))
        self.n_min_q_3.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_65.setText(_translate("MainWindow", "MIN потужність, кВт"))
        self.label_66.setText(_translate("MainWindow", "MIN навантаження, кВт"))
        self.label_67.setText(_translate("MainWindow", "Qmax"))
        self.q_max_dev_3.setText(_translate("MainWindow", "15.18"))
        self.label_69.setText(_translate("MainWindow", "Qmin"))
        self.q_min_dev_3.setText(_translate("MainWindow", "0.051"))
        self.quantity_3.setText(_translate("MainWindow", "1"))
        self.quantity_3.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_71.setText(_translate("MainWindow", "Кількість"))
        self.label_72.setText(_translate("MainWindow", "Прилад 4"))
        self.label_73.setText(_translate("MainWindow", "MAX потужність, кВт"))
        self.n_max_p_4.setText(_translate("MainWindow", "0"))
        self.n_max_p_4.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_74.setText(_translate("MainWindow", "MAX навантаження, кВт"))
        self.n_max_q_4.setText(_translate("MainWindow", "0"))
        self.n_max_q_4.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_75.setText(_translate("MainWindow", "MAX ККД"))
        self.eff_coef_max_4.setText(_translate("MainWindow", "1"))
        self.eff_coef_max_4.setPlaceholderText(_translate("MainWindow", "1"))
        self.eff_coef_min_4.setText(_translate("MainWindow", "1"))
        self.eff_coef_min_4.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_76.setText(_translate("MainWindow", "MIN ККД"))
        self.n_min_p_4.setText(_translate("MainWindow", "0"))
        self.n_min_p_4.setPlaceholderText(_translate("MainWindow", "0"))
        self.n_min_q_4.setText(_translate("MainWindow", "0"))
        self.n_min_q_4.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_77.setText(_translate("MainWindow", "MIN потужність, кВт"))
        self.label_78.setText(_translate("MainWindow", "MIN навантаження, кВт"))
        self.label_79.setText(_translate("MainWindow", "Qmax"))
        self.q_max_dev_4.setText(_translate("MainWindow", "15.18"))
        self.label_81.setText(_translate("MainWindow", "Qmin"))
        self.q_min_dev_4.setText(_translate("MainWindow", "0.051"))
        self.quantity_4.setText(_translate("MainWindow", "1"))
        self.quantity_4.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_83.setText(_translate("MainWindow", "Кількість"))
        self.label_85.setText(_translate("MainWindow", "Povered by"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
