# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(380, 219)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        AuthDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Icons/login_black_36dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AuthDialog.setWindowIcon(icon)
        AuthDialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(127, 172, 229, 255), stop:0.9801 rgba(6, 0, 173, 255), stop:1 rgba(0, 131, 68, 255));")
        self.label = QtWidgets.QLabel(AuthDialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label.setObjectName("label")
        self.login = QtWidgets.QLineEdit(AuthDialog)
        self.login.setGeometry(QtCore.QRect(90, 40, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"\n"
"")
        self.login.setAlignment(QtCore.Qt.AlignCenter)
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(AuthDialog)
        self.label_2.setGeometry(QtCore.QRect(15, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(AuthDialog)
        self.password.setGeometry(QtCore.QRect(90, 90, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.btnCancel = QtWidgets.QPushButton(AuthDialog)
        self.btnCancel.setGeometry(QtCore.QRect(140, 160, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnCancel.setIconSize(QtCore.QSize(28, 20))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOk = QtWidgets.QPushButton(AuthDialog)
        self.btnOk.setGeometry(QtCore.QRect(20, 160, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnOk.setIconSize(QtCore.QSize(28, 20))
        self.btnOk.setObjectName("btnOk")
        self.btnReg = QtWidgets.QPushButton(AuthDialog)
        self.btnReg.setGeometry(QtCore.QRect(260, 160, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnReg.setFont(font)
        self.btnReg.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnReg.setIconSize(QtCore.QSize(28, 20))
        self.btnReg.setObjectName("btnReg")
        self.connection = QtWidgets.QWidget(AuthDialog)
        self.connection.setGeometry(QtCore.QRect(10, 10, 12, 12))
        self.connection.setStyleSheet("background-color: white;\n"
"border: solid 1px white;\n"
"border-radius: 3px;")
        self.connection.setObjectName("connection")
        self.label_3 = QtWidgets.QLabel(AuthDialog)
        self.label_3.setGeometry(QtCore.QRect(30, 6, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(AuthDialog)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Авторизація"))
        self.label.setText(_translate("AuthDialog", "Логін:"))
        self.label_2.setText(_translate("AuthDialog", "Пароль:"))
        self.btnCancel.setText(_translate("AuthDialog", "Відміна"))
        self.btnOk.setText(_translate("AuthDialog", "OK"))
        self.btnReg.setText(_translate("AuthDialog", "Реєстрація"))
        self.label_3.setText(_translate("AuthDialog", "Статус з\'єднання"))
import auth_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthDialog = QtWidgets.QDialog()
    ui = Ui_AuthDialog()
    ui.setupUi(AuthDialog)
    AuthDialog.show()
    sys.exit(app.exec_())
