# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegDialog(object):
    def setupUi(self, RegDialog):
        RegDialog.setObjectName("RegDialog")
        RegDialog.resize(328, 496)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        RegDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/how_to_reg_black_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegDialog.setWindowIcon(icon)
        RegDialog.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(127, 172, 229, 255), stop:0.9801 rgba(6, 0, 173, 255), stop:1 rgba(0, 131, 68, 255));")
        self.label = QtWidgets.QLabel(RegDialog)
        self.label.setGeometry(QtCore.QRect(50, 70, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label.setObjectName("label")
        self.login = QtWidgets.QLineEdit(RegDialog)
        self.login.setGeometry(QtCore.QRect(110, 70, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"\n"
"")
        self.login.setAlignment(QtCore.Qt.AlignCenter)
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(RegDialog)
        self.label_2.setGeometry(QtCore.QRect(35, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(RegDialog)
        self.password.setGeometry(QtCore.QRect(110, 120, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.btnCancel = QtWidgets.QPushButton(RegDialog)
        self.btnCancel.setGeometry(QtCore.QRect(170, 440, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnCancel.setFont(font)
        self.btnCancel.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnCancel.setIconSize(QtCore.QSize(28, 20))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOk = QtWidgets.QPushButton(RegDialog)
        self.btnOk.setGeometry(QtCore.QRect(50, 440, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnOk.setIconSize(QtCore.QSize(28, 20))
        self.btnOk.setObjectName("btnOk")
        self.password_2 = QtWidgets.QLineEdit(RegDialog)
        self.password_2.setGeometry(QtCore.QRect(110, 170, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.password_2.setFont(font)
        self.password_2.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setAlignment(QtCore.Qt.AlignCenter)
        self.password_2.setObjectName("password_2")
        self.label_3 = QtWidgets.QLabel(RegDialog)
        self.label_3.setGeometry(QtCore.QRect(27, 170, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(RegDialog)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.email = QtWidgets.QLineEdit(RegDialog)
        self.email.setGeometry(QtCore.QRect(110, 220, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.email.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        self.label_5 = QtWidgets.QLabel(RegDialog)
        self.label_5.setGeometry(QtCore.QRect(62, 270, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_5.setObjectName("label_5")
        self.name = QtWidgets.QLineEdit(RegDialog)
        self.name.setGeometry(QtCore.QRect(110, 270, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.name.setEchoMode(QtWidgets.QLineEdit.Password)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.label_6 = QtWidgets.QLabel(RegDialog)
        self.label_6.setGeometry(QtCore.QRect(12, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_6.setObjectName("label_6")
        self.password_5 = QtWidgets.QLineEdit(RegDialog)
        self.password_5.setGeometry(QtCore.QRect(110, 320, 200, 26))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.password_5.setFont(font)
        self.password_5.setStyleSheet("background-color: rgba(255,255,255,35);\n"
"border: 2px solid rgba(255,255,255,90);\n"
"border-radius: 5px;\n"
"color: white;\n"
"")
        self.password_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_5.setAlignment(QtCore.Qt.AlignCenter)
        self.password_5.setObjectName("password_5")
        self.label_7 = QtWidgets.QLabel(RegDialog)
        self.label_7.setGeometry(QtCore.QRect(140, 10, 51, 51))
        self.label_7.setStyleSheet("background-color: none;")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/icons/Icons/how_to_reg_white_48dp.svg"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(RegDialog)
        self.label_8.setGeometry(QtCore.QRect(10, 360, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(RegDialog)
        QtCore.QMetaObject.connectSlotsByName(RegDialog)

    def retranslateUi(self, RegDialog):
        _translate = QtCore.QCoreApplication.translate
        RegDialog.setWindowTitle(_translate("RegDialog", "Реєстрація"))
        self.label.setText(_translate("RegDialog", "Логін:"))
        self.label_2.setText(_translate("RegDialog", "Пароль:"))
        self.btnCancel.setText(_translate("RegDialog", "Відміна"))
        self.btnOk.setText(_translate("RegDialog", "OK"))
        self.label_3.setText(_translate("RegDialog", "Пароль*:"))
        self.label_4.setText(_translate("RegDialog", "Email:"))
        self.label_5.setText(_translate("RegDialog", "Ім\'я:"))
        self.label_6.setText(_translate("RegDialog", "Прізвище:"))
        self.label_8.setText(_translate("RegDialog", "Після завершення реєстрації необхідно зачекати деякий час, поки адміністратор візує Вашу заявку."))
import reg_rc
