# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warn_mes_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningMessage(object):
    def setupUi(self, WarningMessage):
        WarningMessage.setObjectName("WarningMessage")
        WarningMessage.resize(476, 219)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        WarningMessage.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/error_outline_black_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WarningMessage.setWindowIcon(icon)
        WarningMessage.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(127, 172, 229, 255), stop:0.9801 rgba(6, 0, 173, 255), stop:1 rgba(0, 131, 68, 255));")
        self.message = QtWidgets.QLabel(WarningMessage)
        self.message.setGeometry(QtCore.QRect(80, 30, 350, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.message.setFont(font)
        self.message.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.message.setObjectName("message")
        self.label_2 = QtWidgets.QLabel(WarningMessage)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/Icons/error_outline_white_48dp.svg"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btnOk = QtWidgets.QPushButton(WarningMessage)
        self.btnOk.setGeometry(QtCore.QRect(180, 160, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnOk.setFont(font)
        self.btnOk.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background-color: rgba(255,255,255,50);\n"
"border: none;\n"
"border-radius: 9px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255,255,255,75);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255,255,255,95);\n"
"}")
        self.btnOk.setIconSize(QtCore.QSize(28, 20))
        self.btnOk.setObjectName("btnOk")
        self.label_3 = QtWidgets.QLabel(WarningMessage)
        self.label_3.setWordWrap(True)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"background-color: none;\n"
"border: none;")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(WarningMessage)
        QtCore.QMetaObject.connectSlotsByName(WarningMessage)

    def retranslateUi(self, WarningMessage):
        _translate = QtCore.QCoreApplication.translate
        WarningMessage.setWindowTitle(_translate("WarningMessage", "Увага!"))
        self.message.setText(_translate("WarningMessage", "Помилка"))
        self.btnOk.setText(_translate("WarningMessage", "OK"))
        self.label_3.setText(_translate("WarningMessage", "Помилка"))
import wm_rc
